### ISSUE TITLE
在一些极端场景下网络结果似乎不太理想

### ISSUE THREAD

**Issue by 98mxr** [hzwer/ResynNet#1]
在一个补帧的专场识别错误后，我输入了以下三帧给ResynNet

参考帧

![0000000](https://user-images.githubusercontent.com/82786769/159116829-824bf59a-310e-461b-9409-60a573c28f93.png)
![0000006](https://user-images.githubusercontent.com/82786769/159116838-e57d9d76-487d-45f0-b07d-bf8455b57a9f.png)

重建帧

![0000001](https://user-images.githubusercontent.com/82786769/159116851-6e6f68ce-a810-4a1e-87ad-e3cd0eff7a30.png)

网络返回了如下结果

![output](https://user-images.githubusercontent.com/82786769/159116863-ff4fc1e9-802a-4900-8b8e-cd1b1dda5ce6.png)

请问大佬有什么办法能解决或者尽量避免这个问题吗

**Comment by hzwer** [comment]
之后可以参考帧故意训练一些不相关帧，但我觉得还是优先从转场识别上解决这个问题
